export enum IDatabaseSchema {
  USER = "USER",
  DESTINATION = "DESTINATION",
  BANNER = "BANNER",
  TESTIMONIAL = "TESTIMONIAL",
  TRIP_DETAILS = "TRIPDETAILS",
  POLICY_DETAILS = "POLICYDETAILS",
  ITINERY_DETAILS = "ITINERYDETAILS"
}
